// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformanceManagement.Models;

namespace PerformanceManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200726085716_add-60")]
    partial class add60
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PerformanceManagement.Models.BehaviouralCompetency", b =>
                {
                    b.Property<int>("BehaviouralCompetencyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("RoleId");

                    b.Property<string>("Title");

                    b.HasKey("BehaviouralCompetencyId");

                    b.ToTable("BehaviouralCompetency");
                });

            modelBuilder.Entity("PerformanceManagement.Models.Coacher.ChartConfirmation", b =>
                {
                    b.Property<int>("ChartConfirmationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EvaluationHierarchyId");

                    b.Property<int>("PeriodDefinitionId");

                    b.Property<string>("CauseDescription");

                    b.Property<bool>("Confirmation");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime?>("EvalHieEffectiveStartDate");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<DateTime?>("SupervisorEffectiveStartDate");

                    b.Property<int>("SupervisorId");

                    b.HasKey("ChartConfirmationId", "EvaluationHierarchyId", "PeriodDefinitionId");

                    b.HasIndex("PeriodDefinitionId");

                    b.HasIndex("EvaluationHierarchyId", "EvalHieEffectiveStartDate");

                    b.HasIndex("SupervisorId", "SupervisorEffectiveStartDate");

                    b.ToTable("ChartConfirmation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.CorrespondentJob", b =>
                {
                    b.Property<int>("CorrespondentJobId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BehaviouralCompetencyId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("JobId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.HasKey("CorrespondentJobId");

                    b.HasIndex("BehaviouralCompetencyId");

                    b.HasIndex("JobId");

                    b.ToTable("CorrespondentJob");
                });

            modelBuilder.Entity("PerformanceManagement.Models.Criteria", b =>
                {
                    b.Property<int>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("LimitOfAdmission");

                    b.Property<int>("TaskId");

                    b.Property<string>("Title");

                    b.HasKey("CriteriaId");

                    b.HasIndex("TaskId");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("PerformanceManagement.Models.CriteriaCalculation", b =>
                {
                    b.Property<int>("CriteriaCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CalculatedCriteriaScore");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CriteriaWeightId");

                    b.Property<int>("EvaluationId");

                    b.Property<string>("RoleId");

                    b.HasKey("CriteriaCalculationId");

                    b.HasIndex("CriteriaWeightId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("CriteriaCalculation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.CriteriaWeight", b =>
                {
                    b.Property<int>("CriteriaWeightId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CriteriaId");

                    b.Property<int>("EvaluationId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.Property<int>("Weight");

                    b.HasKey("CriteriaWeightId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("CriteriaWeight");
                });

            modelBuilder.Entity("PerformanceManagement.Models.CriteriaWeightScore", b =>
                {
                    b.Property<int>("CriteriaWeightScoreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CoacherEffectiveStartDate");

                    b.Property<int?>("CoacherId");

                    b.Property<int?>("CoacherLevel");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CriteriaWeightId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("RoleId");

                    b.Property<int>("Score");

                    b.HasKey("CriteriaWeightScoreId");

                    b.HasIndex("CriteriaWeightId");

                    b.HasIndex("CoacherId", "CoacherEffectiveStartDate");

                    b.ToTable("CriteriaWeightScore");
                });

            modelBuilder.Entity("PerformanceManagement.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AllocatorEvalHieEffcStartDate");

                    b.Property<int?>("AllocatorEvaluationHierarchyId");

                    b.Property<DateTime?>("AllocatorPersonEffecStartDate");

                    b.Property<int>("AllocatorPersonId");

                    b.Property<string>("AllocatorRoleId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EvaluationAcceptanceStatusId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<int>("PeriodDefinitoionId");

                    b.Property<DateTime?>("RecieverAllocEvalHieEffcStartDate");

                    b.Property<DateTime?>("RecieverAllocPersonEffecStartDate");

                    b.Property<int>("RecieverAllocationEvaluationHierarchyId");

                    b.Property<int>("RecieverAllocationPersonId");

                    b.Property<string>("RefutationCause");

                    b.Property<int>("TaskId");

                    b.Property<int?>("TaskWeight");

                    b.HasKey("EvaluationId");

                    b.HasIndex("EvaluationAcceptanceStatusId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.HasIndex("TaskId");

                    b.HasIndex("AllocatorEvaluationHierarchyId", "AllocatorEvalHieEffcStartDate");

                    b.HasIndex("AllocatorPersonId", "AllocatorPersonEffecStartDate");

                    b.HasIndex("RecieverAllocationEvaluationHierarchyId", "RecieverAllocEvalHieEffcStartDate");

                    b.HasIndex("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate");

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationAcceptanceStatus", b =>
                {
                    b.Property<int>("EvaluationAcceptanceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("Title");

                    b.HasKey("EvaluationAcceptanceStatusId");

                    b.ToTable("EvaluationAcceptanceStatus");

                    b.HasData(
                        new
                        {
                            EvaluationAcceptanceStatusId = 1,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 688, DateTimeKind.Local).AddTicks(1999),
                            Title = "تفاهم"
                        },
                        new
                        {
                            EvaluationAcceptanceStatusId = 2,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 690, DateTimeKind.Local).AddTicks(6192),
                            Title = "دستوری"
                        },
                        new
                        {
                            EvaluationAcceptanceStatusId = 3,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 690, DateTimeKind.Local).AddTicks(6212),
                            Title = "صرف نظر"
                        },
                        new
                        {
                            EvaluationAcceptanceStatusId = 4,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 690, DateTimeKind.Local).AddTicks(6215),
                            Title = "نامشخص"
                        });
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationBehaviourCompetencyScore", b =>
                {
                    b.Property<int>("EvaluationBehaviourCompetencyScoreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CoacherEffectiveStartDate");

                    b.Property<int?>("CoacherId");

                    b.Property<int?>("CoacherLevel");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EvaluationBehaviouralCompetencyId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("RoleId");

                    b.Property<int>("Score");

                    b.HasKey("EvaluationBehaviourCompetencyScoreId");

                    b.HasIndex("EvaluationBehaviouralCompetencyId");

                    b.HasIndex("CoacherId", "CoacherEffectiveStartDate");

                    b.ToTable("EvaluationBehaviourCompetencyScore");
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationBehaviouralCompetency", b =>
                {
                    b.Property<int>("EvaluationBehaviouralCompetencyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AllocatorEvalBehavHieEffcStartDate");

                    b.Property<int?>("AllocatorEvaluationBehaviouralHierarchyId");

                    b.Property<DateTime?>("AllocatorPersonEffecStartDate");

                    b.Property<int>("AllocatorPersonId");

                    b.Property<string>("AllocatorRoleId");

                    b.Property<int>("BehaviouralCompetencyId");

                    b.Property<int?>("BehaviouralCompetencyWeight");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EvaluationAcceptanceStatusId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<int>("PeriodDefinitoionId");

                    b.Property<DateTime?>("RecieverAllocEvalBehavHieEffcStartDate");

                    b.Property<DateTime?>("RecieverAllocPersonEffecStartDate");

                    b.Property<int>("RecieverAllocationEvaluationBehaviouralHierarchyId");

                    b.Property<int>("RecieverAllocationPersonId");

                    b.Property<string>("RefutationCause");

                    b.HasKey("EvaluationBehaviouralCompetencyId");

                    b.HasIndex("BehaviouralCompetencyId");

                    b.HasIndex("EvaluationAcceptanceStatusId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.HasIndex("AllocatorEvaluationBehaviouralHierarchyId", "AllocatorEvalBehavHieEffcStartDate");

                    b.HasIndex("AllocatorPersonId", "AllocatorPersonEffecStartDate");

                    b.HasIndex("RecieverAllocationEvaluationBehaviouralHierarchyId", "RecieverAllocEvalBehavHieEffcStartDate");

                    b.HasIndex("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate");

                    b.ToTable("EvaluationBehaviouralCompetency");
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationBehaviouralParticipant", b =>
                {
                    b.Property<int>("EvaluationBehaviouralParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Confirmation");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EvaluationBehaviouralCompetencyId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<DateTime?>("ParticipantEvalBehavHieEffcStartDate");

                    b.Property<int>("ParticipantEvaluationBehaviouralHierarchyId");

                    b.Property<int>("ParticipantId");

                    b.Property<DateTime?>("PeopleEffectiveStartDate");

                    b.Property<DateTime>("RequestDate");

                    b.Property<DateTime?>("ResponseDate");

                    b.Property<int?>("Score");

                    b.HasKey("EvaluationBehaviouralParticipantId");

                    b.HasIndex("EvaluationBehaviouralCompetencyId");

                    b.HasIndex("ParticipantEvaluationBehaviouralHierarchyId", "ParticipantEvalBehavHieEffcStartDate");

                    b.HasIndex("ParticipantId", "PeopleEffectiveStartDate");

                    b.ToTable("EvaluationBehaviouralParticipant");
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationCalculation", b =>
                {
                    b.Property<int>("EvaluationCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CalculatedScore");

                    b.Property<int?>("CoacherDepartmentId");

                    b.Property<int?>("CoacherId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EmployeeDepartmentId");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("EvaluationId");

                    b.Property<int>("PeriodDefinitionId");

                    b.Property<string>("roleId");

                    b.HasKey("EvaluationCalculationId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("EvaluationCalculation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationCompetencyCalculation", b =>
                {
                    b.Property<int>("EvaluationCompetencyCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CalculatedCompetencyScore");

                    b.Property<int>("CoacherDepartmentId");

                    b.Property<int>("CoacherId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EmployeeDepartmentId");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("EvaluationBehaviouralCompetencyId");

                    b.Property<int>("PeriodDefinitionId");

                    b.HasKey("EvaluationCompetencyCalculationId");

                    b.HasIndex("EvaluationBehaviouralCompetencyId");

                    b.ToTable("EvaluationCompetencyCalculation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationParticipant", b =>
                {
                    b.Property<int>("EvaluationParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Confirmation");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EvaluationId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<DateTime?>("ParticipantEvalHieEffcStartDate");

                    b.Property<int>("ParticipantEvaluationHierarchyId");

                    b.Property<int>("ParticipantId");

                    b.Property<DateTime?>("PeopleEffectiveStartDate");

                    b.Property<DateTime>("RequestDate");

                    b.Property<DateTime?>("ResponseDate");

                    b.Property<int?>("Score");

                    b.HasKey("EvaluationParticipantId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ParticipantEvaluationHierarchyId", "ParticipantEvalHieEffcStartDate");

                    b.HasIndex("ParticipantId", "PeopleEffectiveStartDate");

                    b.ToTable("EvaluationParticipant");
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationScore", b =>
                {
                    b.Property<int>("EvaluationScoreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CoacherEffectiveStartDate");

                    b.Property<int?>("CoacherId");

                    b.Property<int?>("CoacherLevel");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EvaluationId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("RoleId");

                    b.Property<int>("Score");

                    b.HasKey("EvaluationScoreId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("CoacherId", "CoacherEffectiveStartDate");

                    b.ToTable("EvaluationScore");
                });

            modelBuilder.Entity("PerformanceManagement.Models.FinalScoreCalculation", b =>
                {
                    b.Property<int>("FinalScoreCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AllocatorEvalHieEffcStartDate");

                    b.Property<int?>("AllocatorEvaluationHierarchyId");

                    b.Property<int?>("AllocatorLevel");

                    b.Property<DateTime?>("AllocatorPersonEffecStartDate");

                    b.Property<int?>("AllocatorPersonId");

                    b.Property<double?>("ApplyPercentToFinalScore");

                    b.Property<string>("CoacherType");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double?>("FinalScore");

                    b.Property<int>("PeriodDefinitoionId");

                    b.Property<DateTime?>("RecieverAllocEvalHieEffcStartDate");

                    b.Property<DateTime?>("RecieverAllocPersonEffecStartDate");

                    b.Property<int>("RecieverAllocationEvaluationHierarchyId");

                    b.Property<int>("RecieverAllocationPersonId");

                    b.HasKey("FinalScoreCalculationId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.HasIndex("AllocatorEvaluationHierarchyId", "AllocatorEvalHieEffcStartDate");

                    b.HasIndex("AllocatorPersonId", "AllocatorPersonEffecStartDate");

                    b.HasIndex("RecieverAllocationEvaluationHierarchyId", "RecieverAllocEvalHieEffcStartDate");

                    b.HasIndex("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate");

                    b.ToTable("FinalScoreCalculation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.FinalScoreCompetencyCalculation", b =>
                {
                    b.Property<int>("FinalScoreCompetencyCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AllocatorEvalHieEffcStartDate");

                    b.Property<int>("AllocatorEvaluationHierarchyId");

                    b.Property<int>("AllocatorLevel");

                    b.Property<DateTime?>("AllocatorPersonEffecStartDate");

                    b.Property<int>("AllocatorPersonId");

                    b.Property<double?>("ApplyPercentToFinalScore");

                    b.Property<string>("CoacherType");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double?>("FinalCompetneciesScore");

                    b.Property<int>("PeriodDefinitoionId");

                    b.Property<DateTime?>("RecieverAllocEvalHieEffcStartDate");

                    b.Property<DateTime?>("RecieverAllocPersonEffecStartDate");

                    b.Property<int>("RecieverAllocationEvaluationHierarchyId");

                    b.Property<int>("RecieverAllocationPersonId");

                    b.HasKey("FinalScoreCompetencyCalculationId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.HasIndex("AllocatorEvaluationHierarchyId", "AllocatorEvalHieEffcStartDate");

                    b.HasIndex("AllocatorPersonId", "AllocatorPersonEffecStartDate");

                    b.HasIndex("RecieverAllocationEvaluationHierarchyId", "RecieverAllocEvalHieEffcStartDate");

                    b.HasIndex("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate");

                    b.ToTable("FinalScoreCompetencyCalculation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.FinalizeCalculation", b =>
                {
                    b.Property<int>("FinalizeCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CoacherEffecStartDate");

                    b.Property<int?>("CocherId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsFinalization");

                    b.Property<int>("PeriodDefinitoionId");

                    b.Property<string>("RoleId");

                    b.HasKey("FinalizeCalculationId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.HasIndex("CocherId", "CoacherEffecStartDate");

                    b.ToTable("FinalizeCalculation");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.Department", b =>
                {
                    b.Property<int>("DepartmentId");

                    b.Property<DateTime>("EffectiveStartDate");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("EffectiveEndDate");

                    b.Property<string>("LongName");

                    b.Property<string>("ShortName");

                    b.HasKey("DepartmentId", "EffectiveStartDate");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.EvaluationCoefficient", b =>
                {
                    b.Property<int>("EvaluationCoefficientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("level1CoacherBWith");

                    b.Property<int>("level1CoacherBWithout");

                    b.Property<int>("level1CoacherTWith");

                    b.Property<int>("level1CoacherTWithout");

                    b.Property<int>("level2CoacherBWith");

                    b.Property<int>("level2CoacherBWithout");

                    b.Property<int>("level2CoacherTWith");

                    b.Property<int>("level2CoacherTWithout");

                    b.Property<int>("participantCoefficientB");

                    b.Property<int>("participantCoefficientT");

                    b.Property<int>("selfEvaluationBWith");

                    b.Property<int>("selfEvaluationBWithout");

                    b.Property<int>("selfEvaluationTWith");

                    b.Property<int>("selfEvaluationTWithout");

                    b.HasKey("EvaluationCoefficientId");

                    b.ToTable("EvaluationCoefficient");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", b =>
                {
                    b.Property<int>("EvaluationHierarchyId");

                    b.Property<DateTime>("EffectiveStartDate");

                    b.Property<DateTime?>("CreatedByEffectiveStartDate");

                    b.Property<int>("CreatedById");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime?>("DepartmentEffectiveStartDate");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("DepartmentType");

                    b.Property<DateTime?>("EffectiveEndDate");

                    b.Property<DateTime?>("LastUpdatedByEffectiveStartDate");

                    b.Property<int?>("LastUpdatedById");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<DateTime?>("ParentEffectiveStartDate");

                    b.Property<int?>("ParentEvaluationHierarchyId");

                    b.Property<DateTime?>("SupervisorEffectiveStartDate");

                    b.Property<int>("SupervisorId");

                    b.HasKey("EvaluationHierarchyId", "EffectiveStartDate");

                    b.HasIndex("CreatedById", "CreatedByEffectiveStartDate");

                    b.HasIndex("DepartmentId", "DepartmentEffectiveStartDate");

                    b.HasIndex("LastUpdatedById", "LastUpdatedByEffectiveStartDate");

                    b.HasIndex("ParentEvaluationHierarchyId", "ParentEffectiveStartDate");

                    b.HasIndex("SupervisorId", "SupervisorEffectiveStartDate");

                    b.ToTable("evaluationHierarchies");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.LikertDescribor", b =>
                {
                    b.Property<int>("LikertDescriborId");

                    b.Property<DateTime>("EffectiveStartDate");

                    b.Property<DateTime?>("EffectiveEndDate");

                    b.Property<DateTime?>("LikertScaleEffectiveStartDate");

                    b.Property<int>("LikertScaleId");

                    b.Property<int>("NumberScale");

                    b.Property<string>("TitleScale");

                    b.HasKey("LikertDescriborId", "EffectiveStartDate");

                    b.HasIndex("LikertScaleId", "LikertScaleEffectiveStartDate");

                    b.ToTable("LikertDescribor");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.LikertScale", b =>
                {
                    b.Property<int>("LikertScaleId");

                    b.Property<DateTime>("EffectiveStartDate");

                    b.Property<DateTime?>("EffectiveEndDate");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("LikertScaleId", "EffectiveStartDate");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("LikertScale");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", b =>
                {
                    b.Property<int>("PeriodDefinitoionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float?>("CompetencyPercent");

                    b.Property<DateTime>("DateFrom");

                    b.Property<DateTime>("DateTo");

                    b.Property<int?>("EvaluationCoefficientId");

                    b.Property<int?>("LackOfScore");

                    b.Property<DateTime?>("LikertScoreWayEffectiveStartDate");

                    b.Property<int?>("LikertScoreWayId");

                    b.Property<DateTime?>("LikertWeightWayBehaiviourEffectiveStartDate");

                    b.Property<int?>("LikertWeightWayBehaiviourId");

                    b.Property<DateTime?>("LikertWeightWayTaskEffectiveStartDate");

                    b.Property<int?>("LikertWeightWayTaskId");

                    b.Property<int>("PeriodCode");

                    b.Property<string>("PeriodTitle")
                        .IsRequired();

                    b.Property<float?>("TaskPercent");

                    b.Property<int?>("WeightWayBehaviour");

                    b.Property<int?>("WeightWayScore");

                    b.Property<int?>("WeightWayTask");

                    b.HasKey("PeriodDefinitoionId");

                    b.HasIndex("EvaluationCoefficientId")
                        .IsUnique()
                        .HasFilter("[EvaluationCoefficientId] IS NOT NULL");

                    b.HasIndex("PeriodCode")
                        .IsUnique();

                    b.HasIndex("PeriodTitle")
                        .IsUnique();

                    b.HasIndex("LikertScoreWayId", "LikertScoreWayEffectiveStartDate");

                    b.HasIndex("LikertWeightWayBehaiviourId", "LikertWeightWayBehaiviourEffectiveStartDate");

                    b.HasIndex("LikertWeightWayTaskId", "LikertWeightWayTaskEffectiveStartDate");

                    b.ToTable("PeriodDefinitoion");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.PersonPeriodEvaluationHierarchy", b =>
                {
                    b.Property<int>("PersonPeriodEvaluationHierarchyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EvaluationHierarchyEffectiveStartDate");

                    b.Property<int>("EvaluationHierarchyId");

                    b.Property<DateTime?>("PeopleEffectiveStartDate");

                    b.Property<int>("PeopleId");

                    b.Property<int>("PeriodDefinitoionId");

                    b.HasKey("PersonPeriodEvaluationHierarchyId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.HasIndex("EvaluationHierarchyId", "EvaluationHierarchyEffectiveStartDate");

                    b.HasIndex("PeopleId", "PeopleEffectiveStartDate");

                    b.ToTable("PersonPeriodEvaluationHierarchy");
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.SectionPeriod", b =>
                {
                    b.Property<int>("SectionPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFrom");

                    b.Property<DateTime>("DateTo");

                    b.Property<int>("PeriodDefinitoionId");

                    b.Property<int>("StatusCode");

                    b.HasKey("SectionPeriodId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.ToTable("SectionPeriod");
                });

            modelBuilder.Entity("PerformanceManagement.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("Title");

                    b.HasKey("JobId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("PerformanceManagement.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AllocatorHierarchyId");

                    b.Property<int>("AllocatorPersonId");

                    b.Property<string>("AllocatorRoleId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int?>("EvaluationId");

                    b.Property<int?>("NotificationTitleId");

                    b.Property<int?>("PeriodDefinitionId");

                    b.Property<int?>("ReceiverHierarchtId");

                    b.Property<int>("ReceiverPersonId");

                    b.Property<string>("ReceiverRoleId");

                    b.Property<string>("Title");

                    b.Property<bool>("Visibility");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTitleId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("PerformanceManagement.Models.NotificationTitle", b =>
                {
                    b.Property<int>("NotificationTitleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Title");

                    b.HasKey("NotificationTitleId");

                    b.ToTable("NotificationTitle");

                    b.HasData(
                        new
                        {
                            NotificationTitleId = 1,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 694, DateTimeKind.Local).AddTicks(9178),
                            Title = "تغییر وضعیت تفاهم وظایف"
                        },
                        new
                        {
                            NotificationTitleId = 2,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 694, DateTimeKind.Local).AddTicks(9904),
                            Title = "تغییر وضعیت تفاهم شایستگی ها"
                        },
                        new
                        {
                            NotificationTitleId = 3,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 694, DateTimeKind.Local).AddTicks(9918),
                            Title = "تعیین وضعیت سایرارزیاب وظایف"
                        },
                        new
                        {
                            NotificationTitleId = 4,
                            CreatedDate = new DateTime(2020, 7, 26, 13, 27, 15, 694, DateTimeKind.Local).AddTicks(9922),
                            Title = "تعیین وضعیت سایر ارزیاب شایستگی رفتاری"
                        });
                });

            modelBuilder.Entity("PerformanceManagement.Models.People", b =>
                {
                    b.Property<int>("PeopleId");

                    b.Property<DateTime>("EffectiveStartDate");

                    b.Property<DateTime?>("EffectiveEndDate");

                    b.Property<DateTime?>("EvaluationHierarchyDate");

                    b.Property<int?>("EvaluationHierarchyID");

                    b.Property<string>("FirstName");

                    b.Property<int?>("JobId");

                    b.Property<string>("LastName");

                    b.Property<int?>("PositionType");

                    b.Property<int?>("changeStatus");

                    b.HasKey("PeopleId", "EffectiveStartDate");

                    b.HasIndex("JobId");

                    b.HasIndex("EvaluationHierarchyID", "EvaluationHierarchyDate");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PerformanceManagement.Models.PublicTask", b =>
                {
                    b.Property<int>("PublicTaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CorrespondentTaskId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<int>("TaskId");

                    b.HasKey("PublicTaskId");

                    b.HasIndex("CorrespondentTaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("PublicTask");
                });

            modelBuilder.Entity("PerformanceManagement.Models.RelatedCompetencyWithSensibleEvent", b =>
                {
                    b.Property<int>("RelatedCompetencyWithSensibleEventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BehaviouralCompetencyId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("SensibleEventId");

                    b.HasKey("RelatedCompetencyWithSensibleEventId");

                    b.HasIndex("BehaviouralCompetencyId");

                    b.HasIndex("SensibleEventId");

                    b.ToTable("RelatedCompetencyWithSensibleEvent");
                });

            modelBuilder.Entity("PerformanceManagement.Models.RelatedPeopleWithSensibleEvent", b =>
                {
                    b.Property<int>("RelatedPeopleWithSensibleEventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime?>("DepartmentEffectiveStartDate");

                    b.Property<int>("DepartmentId");

                    b.Property<DateTime?>("EmployeeEffectiveStartDate");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("SensibleEventId");

                    b.HasKey("RelatedPeopleWithSensibleEventId");

                    b.HasIndex("SensibleEventId");

                    b.HasIndex("DepartmentId", "DepartmentEffectiveStartDate");

                    b.HasIndex("EmployeeId", "EmployeeEffectiveStartDate");

                    b.ToTable("RelatedPeopleWithSensibleEvent");
                });

            modelBuilder.Entity("PerformanceManagement.Models.RelatedTaskWithSensibleEvent", b =>
                {
                    b.Property<int>("RelatedTaskWithSensibleEventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("SensibleEventId");

                    b.Property<int>("TaskId");

                    b.HasKey("RelatedTaskWithSensibleEventId");

                    b.HasIndex("SensibleEventId");

                    b.HasIndex("TaskId");

                    b.ToTable("RelatedTaskWithSensibleEvent");
                });

            modelBuilder.Entity("PerformanceManagement.Models.SensibleEvent", b =>
                {
                    b.Property<int>("SensibleEventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime?>("DepartmentEffectiveStartDate");

                    b.Property<int>("EventType");

                    b.Property<int>("ImportantWeight");

                    b.Property<int>("PersonDepartmentId");

                    b.Property<DateTime?>("PersonEffectiveStartDate");

                    b.Property<int>("PersonId");

                    b.Property<string>("PersonRole");

                    b.Property<DateTime>("SensibleEventDate");

                    b.Property<string>("Title");

                    b.Property<bool>("Visibility");

                    b.HasKey("SensibleEventId");

                    b.HasIndex("PersonDepartmentId", "DepartmentEffectiveStartDate");

                    b.HasIndex("PersonId", "PersonEffectiveStartDate");

                    b.ToTable("SensibleEvent");
                });

            modelBuilder.Entity("PerformanceManagement.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EvaluationHierarchyEffectiveStartDate");

                    b.Property<int?>("EvaluationHierarchyId");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<int?>("ParentTaskId");

                    b.Property<int?>("PeriodDefinitoionId");

                    b.Property<int>("ResourceType");

                    b.Property<string>("RoleId");

                    b.Property<string>("Title");

                    b.Property<int?>("Type");

                    b.HasKey("TaskId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("PeriodDefinitoionId");

                    b.HasIndex("EvaluationHierarchyId", "EvaluationHierarchyEffectiveStartDate");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("PerformanceManagement.Models.TrainingNeed", b =>
                {
                    b.Property<int>("TrainingNeedId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int>("EvaluationId");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("Title");

                    b.HasKey("TrainingNeedId");

                    b.HasIndex("EvaluationId");

                    b.ToTable("TrainingNeed");
                });

            modelBuilder.Entity("PerformanceManagement.Models.Truth", b =>
                {
                    b.Property<int>("TruthId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BehaviouralCompetencyId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("LastUpdatedBy");

                    b.Property<DateTime?>("LastUpdatedDate");

                    b.Property<string>("Title");

                    b.HasKey("TruthId");

                    b.HasIndex("BehaviouralCompetencyId");

                    b.ToTable("Truth");
                });

            modelBuilder.Entity("PerformanceManagement.Models.ICTAdmin.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate");

                    b.Property<DateTime?>("PeopleEffectiveStartDate");

                    b.Property<int?>("PeopleId");

                    b.HasIndex("PeopleId", "PeopleEffectiveStartDate");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PerformanceManagement.Models.Coacher.ChartConfirmation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "PeriodDefinitoion")
                        .WithMany("ChartConfirmations")
                        .HasForeignKey("PeriodDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "EvaluationHierarchy")
                        .WithMany("ChartConfirmations")
                        .HasForeignKey("EvaluationHierarchyId", "EvalHieEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Supervisor")
                        .WithMany("ChartConfirmations")
                        .HasForeignKey("SupervisorId", "SupervisorEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.CorrespondentJob", b =>
                {
                    b.HasOne("PerformanceManagement.Models.BehaviouralCompetency", "BehaviouralCompetency")
                        .WithMany("CorrespondentJobs")
                        .HasForeignKey("BehaviouralCompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.Job", "Job")
                        .WithMany("CorrespondentJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.Criteria", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Task", "Task")
                        .WithMany("Criterias")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.CriteriaCalculation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.CriteriaWeight", "CriteriaWeight")
                        .WithMany("CriteriaCalculations")
                        .HasForeignKey("CriteriaWeightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PerformanceManagement.Models.Evaluation", "Evaluation")
                        .WithMany("CriteriaCalculations")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.CriteriaWeight", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Criteria", "Criteria")
                        .WithMany("CriteriaWeights")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.Evaluation", "Evaluation")
                        .WithMany("CriteriaWeights")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.CriteriaWeightScore", b =>
                {
                    b.HasOne("PerformanceManagement.Models.CriteriaWeight", "CriteriaWeight")
                        .WithMany("CriteriaWeightScores")
                        .HasForeignKey("CriteriaWeightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PerformanceManagement.Models.People", "Coacher")
                        .WithMany("CriteriaWeightScores")
                        .HasForeignKey("CoacherId", "CoacherEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.Evaluation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.EvaluationAcceptanceStatus", "EvaluationAcceptanceStatus")
                        .WithMany("Evaluations")
                        .HasForeignKey("EvaluationAcceptanceStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "PeriodDefinitoion")
                        .WithMany("Evaluations")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.Task", "Task")
                        .WithMany("Evaluations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "AllocatorEvaluationHierarchy")
                        .WithMany("AllocatorEvaluationHierarchies")
                        .HasForeignKey("AllocatorEvaluationHierarchyId", "AllocatorEvalHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Allocator")
                        .WithMany("Allocators")
                        .HasForeignKey("AllocatorPersonId", "AllocatorPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "RecieverAllocationEvaluationHierarchy")
                        .WithMany("RecieverAllocationEvaluationHierarchies")
                        .HasForeignKey("RecieverAllocationEvaluationHierarchyId", "RecieverAllocEvalHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "RecieverAllocation")
                        .WithMany("RecieversAllocation")
                        .HasForeignKey("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationBehaviourCompetencyScore", b =>
                {
                    b.HasOne("PerformanceManagement.Models.EvaluationBehaviouralCompetency", "EvaluationBehaviouralCompetency")
                        .WithMany("EvaluationBehaviourCompetencyScores")
                        .HasForeignKey("EvaluationBehaviouralCompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Coacher")
                        .WithMany("EvaluationBehaviourCompetencyScores")
                        .HasForeignKey("CoacherId", "CoacherEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationBehaviouralCompetency", b =>
                {
                    b.HasOne("PerformanceManagement.Models.BehaviouralCompetency", "BehaviouralCompetency")
                        .WithMany("EvaluationBehaviouralCompetencies")
                        .HasForeignKey("BehaviouralCompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.EvaluationAcceptanceStatus", "EvaluationAcceptanceStatus")
                        .WithMany("EvaluationBehaviouralCompetencies")
                        .HasForeignKey("EvaluationAcceptanceStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "PeriodDefinitoion")
                        .WithMany("EvaluationBehaviouralCompetencies")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "AllocatorEvaluationBehaviouralHierarchy")
                        .WithMany("AllocatorEvaluationBehaviouralHierarchies")
                        .HasForeignKey("AllocatorEvaluationBehaviouralHierarchyId", "AllocatorEvalBehavHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Allocator")
                        .WithMany("AllocatorsEvaluationBehavioural")
                        .HasForeignKey("AllocatorPersonId", "AllocatorPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "RecieverAllocationEvaluationBehaviouralHierarchy")
                        .WithMany("RecieverAllocationEvaluationBehaviouralHierarchies")
                        .HasForeignKey("RecieverAllocationEvaluationBehaviouralHierarchyId", "RecieverAllocEvalBehavHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "RecieverAllocation")
                        .WithMany("RecieversAllocationEvaluationBehavioural")
                        .HasForeignKey("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationBehaviouralParticipant", b =>
                {
                    b.HasOne("PerformanceManagement.Models.EvaluationBehaviouralCompetency", "EvaluationBehaviouralCompetency")
                        .WithMany("EvaluationBehaviouralParticipants")
                        .HasForeignKey("EvaluationBehaviouralCompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "ParticipantEvaluationBehaviouralHierarchy")
                        .WithMany("EvaluationBehaviouralParticipants")
                        .HasForeignKey("ParticipantEvaluationBehaviouralHierarchyId", "ParticipantEvalBehavHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Participant")
                        .WithMany("EvaluationBehaviouralParticipants")
                        .HasForeignKey("ParticipantId", "PeopleEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationCalculation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationCalculations")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationCompetencyCalculation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.EvaluationBehaviouralCompetency", "EvaluationBehaviouralCompetency")
                        .WithMany("EvaluationCompetencyCalculations")
                        .HasForeignKey("EvaluationBehaviouralCompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationParticipant", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationParticipants")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "ParticipantEvaluationHierarchy")
                        .WithMany("EvaluationParticipants")
                        .HasForeignKey("ParticipantEvaluationHierarchyId", "ParticipantEvalHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Participant")
                        .WithMany("EvaluationParticipants")
                        .HasForeignKey("ParticipantId", "PeopleEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.EvaluationScore", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationScores")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Coacher")
                        .WithMany("EvaluationScores")
                        .HasForeignKey("CoacherId", "CoacherEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.FinalScoreCalculation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "PeriodDefinitoion")
                        .WithMany("FinalScoreCalculations")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "AllocatorEvaluationHierarchy")
                        .WithMany("AllocatorFinalScoreCalculations")
                        .HasForeignKey("AllocatorEvaluationHierarchyId", "AllocatorEvalHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Allocator")
                        .WithMany("AllocatorFinalScoreCalculations")
                        .HasForeignKey("AllocatorPersonId", "AllocatorPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "RecieverAllocationEvaluationHierarchy")
                        .WithMany("RecieverFinalScoreCalculations")
                        .HasForeignKey("RecieverAllocationEvaluationHierarchyId", "RecieverAllocEvalHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "RecieverAllocation")
                        .WithMany("RecieverFinalScoreCalculations")
                        .HasForeignKey("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.FinalScoreCompetencyCalculation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "PeriodDefinitoion")
                        .WithMany("FinalScoreCompetencyCalculations")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "AllocatorEvaluationHierarchy")
                        .WithMany("AllocatorFinalScoreCompetencyCalculations")
                        .HasForeignKey("AllocatorEvaluationHierarchyId", "AllocatorEvalHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Allocator")
                        .WithMany("AllocatorFinalScoreCompetencyCalculations")
                        .HasForeignKey("AllocatorPersonId", "AllocatorPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "RecieverAllocationEvaluationHierarchy")
                        .WithMany("RecieverFinalScoreCompetencyCalculations")
                        .HasForeignKey("RecieverAllocationEvaluationHierarchyId", "RecieverAllocEvalHieEffcStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "RecieverAllocation")
                        .WithMany("RecieverFinalScoreCompetencyCalculations")
                        .HasForeignKey("RecieverAllocationPersonId", "RecieverAllocPersonEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.FinalizeCalculation", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "PeriodDefinitoion")
                        .WithMany("FinalizeCalculations")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Coacher")
                        .WithMany("FinalizeCalculations")
                        .HasForeignKey("CocherId", "CoacherEffecStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", b =>
                {
                    b.HasOne("PerformanceManagement.Models.People", "CreatedBy")
                        .WithMany("Createdby")
                        .HasForeignKey("CreatedById", "CreatedByEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.Department", "Department")
                        .WithMany("EvaluationHierarchies")
                        .HasForeignKey("DepartmentId", "DepartmentEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "LastUpdatedBy")
                        .WithMany("LastUpdatedBy")
                        .HasForeignKey("LastUpdatedById", "LastUpdatedByEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentEvaluationHierarchyId", "ParentEffectiveStartDate");

                    b.HasOne("PerformanceManagement.Models.People", "Supervisor")
                        .WithMany("EvaluationHierarchies")
                        .HasForeignKey("SupervisorId", "SupervisorEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.LikertDescribor", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.LikertScale", "LikertScale")
                        .WithMany("LikertDescribors")
                        .HasForeignKey("LikertScaleId", "LikertScaleEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationCoefficient", "EvaluationCoefficient")
                        .WithOne("PeriodDefinitoion")
                        .HasForeignKey("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "EvaluationCoefficientId");

                    b.HasOne("PerformanceManagement.Models.HRAdmin.LikertScale", "LikertScoreWay")
                        .WithMany("periodDefinitoionLikertScoreWay")
                        .HasForeignKey("LikertScoreWayId", "LikertScoreWayEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.LikertScale", "LikertWeightWayBehaiviour")
                        .WithMany("periodDefinitoionLikertBehaiviour")
                        .HasForeignKey("LikertWeightWayBehaiviourId", "LikertWeightWayBehaiviourEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.LikertScale", "LikertWeightWayTask")
                        .WithMany("periodDefinitoionLikertTask")
                        .HasForeignKey("LikertWeightWayTaskId", "LikertWeightWayTaskEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.PersonPeriodEvaluationHierarchy", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "periodDefinitoion")
                        .WithMany("PersonAndPeriods")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "evaluationHierarchy")
                        .WithMany("PersonAndPeriodAndEvaluationHierarchies")
                        .HasForeignKey("EvaluationHierarchyId", "EvaluationHierarchyEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "people")
                        .WithMany("PersonAndPeriods")
                        .HasForeignKey("PeopleId", "PeopleEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.HRAdmin.SectionPeriod", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "periodDefinitoion")
                        .WithMany("SectionPeriods")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.Notification", b =>
                {
                    b.HasOne("PerformanceManagement.Models.NotificationTitle", "NotificationTitle")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTitleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.People", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Job", "Job")
                        .WithMany("Peoples")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "evaluationHierarchy")
                        .WithMany("peopledepartmentHierarchy")
                        .HasForeignKey("EvaluationHierarchyID", "EvaluationHierarchyDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.PublicTask", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Task", "CorrespondentTask")
                        .WithMany("CorrespondentTasks")
                        .HasForeignKey("CorrespondentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.Task", "Task")
                        .WithMany("PublicTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.RelatedCompetencyWithSensibleEvent", b =>
                {
                    b.HasOne("PerformanceManagement.Models.BehaviouralCompetency", "BehaviouralCompetency")
                        .WithMany("RelatedCompetencyWithSensibleEvents")
                        .HasForeignKey("BehaviouralCompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.SensibleEvent", "SensibleEvent")
                        .WithMany("RelatedCompetencyWithSensibleEvents")
                        .HasForeignKey("SensibleEventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.RelatedPeopleWithSensibleEvent", b =>
                {
                    b.HasOne("PerformanceManagement.Models.SensibleEvent", "SensibleEvent")
                        .WithMany("RelatedPeopleWithSensibleEvents")
                        .HasForeignKey("SensibleEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "Department")
                        .WithMany("RelatedPeopleWithSensibleEvents")
                        .HasForeignKey("DepartmentId", "DepartmentEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Employee")
                        .WithMany("RelatedPeopleWithSensibleEvents")
                        .HasForeignKey("EmployeeId", "EmployeeEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.RelatedTaskWithSensibleEvent", b =>
                {
                    b.HasOne("PerformanceManagement.Models.SensibleEvent", "SensibleEvent")
                        .WithMany("RelatedTaskWithSensibleEvents")
                        .HasForeignKey("SensibleEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.Task", "Task")
                        .WithMany("RelatedTaskWithSensibleEvents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.SensibleEvent", b =>
                {
                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "PersonDepartment")
                        .WithMany("SensibleEvents")
                        .HasForeignKey("PersonDepartmentId", "DepartmentEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.People", "Person")
                        .WithMany("SensibleEvents")
                        .HasForeignKey("PersonId", "PersonEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.Task", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Task", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTaskId");

                    b.HasOne("PerformanceManagement.Models.HRAdmin.PeriodDefinitoion", "PeriodDefinitoion")
                        .WithMany("Tasks")
                        .HasForeignKey("PeriodDefinitoionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerformanceManagement.Models.HRAdmin.EvaluationHierarchy", "EvaluationHierarchy")
                        .WithMany("Tasks")
                        .HasForeignKey("EvaluationHierarchyId", "EvaluationHierarchyEffectiveStartDate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.TrainingNeed", b =>
                {
                    b.HasOne("PerformanceManagement.Models.Evaluation", "Evaluation")
                        .WithMany("TrainingNeeds")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.Truth", b =>
                {
                    b.HasOne("PerformanceManagement.Models.BehaviouralCompetency", "BehaviouralCompetency")
                        .WithMany("Truths")
                        .HasForeignKey("BehaviouralCompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PerformanceManagement.Models.ICTAdmin.ApplicationUser", b =>
                {
                    b.HasOne("PerformanceManagement.Models.People", "People")
                        .WithMany()
                        .HasForeignKey("PeopleId", "PeopleEffectiveStartDate");
                });
#pragma warning restore 612, 618
        }
    }
}
